[project]
name = "whisper-trans"
version = "0.1.0"
description = "CLI-утилита на базе OpenAI Whisper для транскрибации аудио в текст"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["openai-whisper>=20240930"]
